import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import {
  awaitOpeningPromptReceipt,
  CLIPPED_OPENING_PROMPT_PREFACE,
  compareOpeningPromptReceipt,
  firstUserTurnText,
} from "./opening-prompt-receipt.ts";
import { deliverAgentOpeningPrompt } from "./opening-prompt.ts";
import { baseDeps, baseRequest } from "./policy-test-fixtures.ts";
import { HARNESS_NAMES } from "../harness-routing/harness.ts";
import type { PolicyResolution } from "./create.types.ts";
import type { MessageQueueStore } from "../message-queue/message-queue.store.ts";
import type { HerdrAgent } from "../herdr/herdr-inventory.service.ts";

const OPENING_PROMPT =
  "You are `stager-eighth` (Stager). Your supervisor is `Regent`.\n\n" +
  "Once a plan is consolidated, run `add-to-queue` (never rewrite or reorder existing entries), " +
  "then `send-agent` the Regent that a plan is complete.";
const CLIPPED_TAIL =
  "order existing entries), then `send-agent` the Regent that a plan is complete.";

function transcriptLine(record: object): string {
  return `${JSON.stringify(record)}\n`;
}

function transcriptWithFirstUserTurn(content: unknown): string {
  return (
    transcriptLine({ type: "last-prompt" }) +
    transcriptLine({ type: "attachment", message: { role: "user", content: "hook output" } }) +
    transcriptLine({
      type: "user",
      isMeta: true,
      message: { role: "user", content: "Caveat: generated by the harness" },
    }) +
    transcriptLine({ type: "user", message: { role: "user", content } }) +
    transcriptLine({
      type: "assistant",
      message: { role: "assistant", model: "claude-sonnet-5", content: [] },
    })
  );
}

test("firstUserTurnText skips startup, attachment and meta records and reads string or block content", () => {
  assert.equal(
    firstUserTurnText(transcriptWithFirstUserTurn(OPENING_PROMPT)),
    OPENING_PROMPT,
  );
  assert.equal(
    firstUserTurnText(
      transcriptWithFirstUserTurn([
        { type: "text", text: "first " },
        { type: "text", text: "second" },
      ]),
    ),
    "first second",
  );
  assert.equal(firstUserTurnText(transcriptLine({ type: "attachment" })), undefined);
});

test("compareOpeningPromptReceipt reports the clipped tail that reached stager-eighth as clipped", () => {
  const receipt = compareOpeningPromptReceipt(
    OPENING_PROMPT,
    transcriptWithFirstUserTurn(CLIPPED_TAIL),
    "/transcripts/stager.jsonl",
  );
  assert.equal(receipt.status, "clipped");
  assert.equal(receipt.status === "clipped" && receipt.receivedText, CLIPPED_TAIL);
});

test("compareOpeningPromptReceipt tolerates whitespace re-wrapping but nothing else", () => {
  const rewrapped = OPENING_PROMPT.replace(/\n\n/gu, " \n ");
  assert.equal(
    compareOpeningPromptReceipt(OPENING_PROMPT, transcriptWithFirstUserTurn(rewrapped), "/t").status,
    "intact",
  );
  assert.equal(
    compareOpeningPromptReceipt(OPENING_PROMPT, transcriptWithFirstUserTurn(`${OPENING_PROMPT} extra`), "/t").status,
    "clipped",
  );
  assert.equal(
    compareOpeningPromptReceipt(OPENING_PROMPT, transcriptLine({ type: "last-prompt" }), "/t").status,
    "unobserved",
  );
});

test("awaitOpeningPromptReceipt polls the spawned agent's own transcript until its first user turn exists", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "opening-prompt-receipt-"));
  const baseDir = path.join(root, "data");
  const projectsDir = path.join(root, "projects");
  const cwd = path.join(root, "worktree");
  await mkdir(path.join(baseDir, "stager-test"), { recursive: true });
  await writeFile(
    path.join(baseDir, "stager-test", "spawn.json"),
    JSON.stringify({ harness: "claude", model: "sonnet", effort: 1, cwd, session_id: "abc" }),
  );
  const projectDirectory = path.join(projectsDir, cwd.replace(/[^a-zA-Z0-9-]/g, "-"));
  await mkdir(projectDirectory, { recursive: true });
  let clock = 0;
  let polls = 0;
  const receipt = await awaitOpeningPromptReceipt("stager-test", OPENING_PROMPT, {
    baseDir,
    projectsDir,
    pollIntervalMs: 10,
    deadlineMs: 1_000,
    now: () => clock,
    sleep: async () => {
      clock += 10;
      polls += 1;
      if (polls === 2) {
        await writeFile(
          path.join(projectDirectory, "abc.jsonl"),
          transcriptWithFirstUserTurn(CLIPPED_TAIL),
        );
      }
    },
  });
  assert.equal(receipt.status, "clipped");
  assert.equal(polls, 2);
});

test("awaitOpeningPromptReceipt gives up as unobserved at the deadline without a transcript", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "opening-prompt-receipt-"));
  let clock = 0;
  const receipt = await awaitOpeningPromptReceipt("nobody", OPENING_PROMPT, {
    baseDir: path.join(root, "data"),
    projectsDir: path.join(root, "projects"),
    pollIntervalMs: 10,
    deadlineMs: 30,
    now: () => clock,
    sleep: async () => {
      clock += 10;
    },
  });
  assert.equal(receipt.status, "unobserved");
});

function fakeQueue(): { store: MessageQueueStore; prompts: string[] } {
  const prompts: string[] = [];
  const store = {
    insertWorkItem: (item: { payload: { prompt: string } }) => {
      prompts.push(item.payload.prompt);
      return { id: prompts.length };
    },
    close: () => {},
  } as unknown as MessageQueueStore;
  return { store, prompts };
}

function claudeRequest(overrides: Partial<PolicyResolution> = {}): PolicyResolution {
  return {
    ...baseRequest(),
    launchEffort: 1,
    routingNote: "",
    durableRoutingNote: false,
    capabilityOverrideNote: "",
    effortOverrideNote: "",
    harnessOverrideNote: "",
    ...overrides,
  } as PolicyResolution;
}

const REGISTERED_AGENT = {
  agent: "claude",
  name: "shadow-brg-01",
  agentStatus: "idle",
  cwd: "/tmp/shadow-brg-01",
  focused: false,
  paneId: "w1:p1",
  tabId: "w1:t1",
  terminalId: "term_1",
} as HerdrAgent;

test("a clipped receipt re-enqueues the complete opening prompt behind a preface and reports it", async () => {
  const { store, prompts } = fakeQueue();
  const stderr: string[] = [];
  const result = await deliverAgentOpeningPrompt(
    claudeRequest(),
    baseDeps({
      resolveAgent: async () => REGISTERED_AGENT,
      openMessageQueueStore: () => store,
      writeStderr: (text) => stderr.push(text),
      awaitOpeningPromptReceipt: async () => ({
        status: "clipped",
        receivedText: CLIPPED_TAIL,
        transcriptPath: "/t/abc.jsonl",
      }),
    }),
    OPENING_PROMPT,
    true,
  );
  assert.deepEqual(result, {
    delivered: true,
    outcome: "not-applicable",
    receipt: "clipped-resent",
  });
  assert.equal(prompts.length, 2);
  assert.equal(prompts[0], OPENING_PROMPT);
  assert.equal(prompts[1], `${CLIPPED_OPENING_PROMPT_PREFACE}\n\n${OPENING_PROMPT}`);
  assert.match(stderr.join(""), /CLIPPED opening prompt/);
  assert.match(stderr.join(""), new RegExp(`${CLIPPED_TAIL.length} of ${OPENING_PROMPT.length} characters`));
});

test("an intact receipt leaves the single enqueue alone", async () => {
  const { store, prompts } = fakeQueue();
  const result = await deliverAgentOpeningPrompt(
    claudeRequest(),
    baseDeps({
      resolveAgent: async () => REGISTERED_AGENT,
      openMessageQueueStore: () => store,
      awaitOpeningPromptReceipt: async () => ({ status: "intact", transcriptPath: "/t/abc.jsonl" }),
    }),
    OPENING_PROMPT,
    true,
  );
  assert.equal(result.receipt, "intact");
  assert.equal(prompts.length, 1);
});

test("receipt verification is not applied to a Codex spawn", async () => {
  const { store, prompts } = fakeQueue();
  let receiptChecks = 0;
  const result = await deliverAgentOpeningPrompt(
    claudeRequest({ launchHarness: HARNESS_NAMES.CODEX }),
    baseDeps({
      resolveAgent: async () => ({ ...REGISTERED_AGENT, agent: "codex" }),
      openMessageQueueStore: () => store,
      awaitOpeningPromptReceipt: async () => {
        receiptChecks += 1;
        return { status: "intact", transcriptPath: "/t" };
      },
    }),
    OPENING_PROMPT,
    true,
  );
  assert.equal(result.receipt, "not-applicable");
  assert.equal(receiptChecks, 0);
  assert.equal(prompts.length, 1);
});
